// Generated by scripts/discover-pools.mjs on 2026-09-04.
// Every field was read from Robinhood Chain; do not hand-edit. Regenerate with:
//   node scripts/discover-pools.mjs

export type EquityAsset = {
  /** Ticker as the token reports it. */
  symbol: string;
  name: string;
  address: `0x${string}`;
  decimals: number;
  /** Deepest Uniswap v3 pool against USDG that stores enough observations for a 30-minute TWAP. */
  pool: `0x${string}`;
  fee: number;
  /** True when the equity is the pool's token0. Getting this wrong inverts every price. */
  assetIsToken0: boolean;
  observationCardinality: number;
  chainLiquidityUsd: number;
  holders: number | null;
};

export const USDG = "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168" as const;
export const UNISWAP_V3_FACTORY = "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA" as const;

/** Tokenized equities with a USDG pool deep enough to price and liquidate against. */
export const EQUITY_ASSETS: readonly EquityAsset[] = [
  {
    "symbol": "SPY",
    "name": "SPDR S&P 500 ETF Trust • Robinhood Token",
    "address": "0x117cc2133c37B721F49dE2A7a74833232B3B4C0C",
    "decimals": 18,
    "pool": "0xa7Bb1AC63BBaB0C44316E6c8C455213441689167",
    "fee": 500,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 8460839,
    "holders": 51254
  },
  {
    "symbol": "NVDA",
    "name": "NVIDIA • Robinhood Token",
    "address": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
    "decimals": 18,
    "pool": "0xd4EB21209C4D6093f80B5b84f5C45cc093EA14a3",
    "fee": 500,
    "assetIsToken0": false,
    "observationCardinality": 6000,
    "chainLiquidityUsd": 7138045,
    "holders": 92177
  },
  {
    "symbol": "SPCX",
    "name": "Space Exploration Technologies Corp. Class A Common Stock • Robinhood Token",
    "address": "0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa",
    "decimals": 18,
    "pool": "0xc61284332117c3FB23A2A56cceFFD07F7aF60029",
    "fee": 500,
    "assetIsToken0": true,
    "observationCardinality": 3100,
    "chainLiquidityUsd": 3931721,
    "holders": 71501
  },
  {
    "symbol": "MU",
    "name": "Micron Technology • Robinhood Token",
    "address": "0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD",
    "decimals": 18,
    "pool": "0xd057B1Bc54917855BBee58eAd58647f47caB35E5",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 2560719,
    "holders": 30917
  },
  {
    "symbol": "AAPL",
    "name": "Apple • Robinhood Token",
    "address": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9",
    "decimals": 18,
    "pool": "0xAae0d815EE56e4092a5E5C2911E676Fea50B2d6D",
    "fee": 500,
    "assetIsToken0": false,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 2381954,
    "holders": 61517
  },
  {
    "symbol": "QQQ",
    "name": "Invesco QQQ • Robinhood Token",
    "address": "0xD5f3879160bc7c32ebb4dC785F8a4F505888de68",
    "decimals": 18,
    "pool": "0xD60A5d14dB690B7Afad71F76B108071D7175597d",
    "fee": 500,
    "assetIsToken0": false,
    "observationCardinality": 300,
    "chainLiquidityUsd": 1940895,
    "holders": 15762
  },
  {
    "symbol": "HIMS",
    "name": "Hims & Hers Health • Robinhood Token",
    "address": "0xCceE82fE024c36fA15E1005edE3E9e4787e23D09",
    "decimals": 18,
    "pool": "0xC8C90d3a1c1a24967E773ac2aD0d456BA3E31F64",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 360,
    "chainLiquidityUsd": 1932520,
    "holders": 3134
  },
  {
    "symbol": "GLD",
    "name": "SPDR Gold Shares • Robinhood Token",
    "address": "0xC9a981FEE1F9DEc688bb123ccDeCc63D0deBFC4e",
    "decimals": 18,
    "pool": "0x7A6A053eCCf1446A2633E05aA6D40D09381997ec",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 1742877,
    "holders": 14139
  },
  {
    "symbol": "TSLA",
    "name": "Tesla • Robinhood Token",
    "address": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d",
    "decimals": 18,
    "pool": "0xf4ACdAEEB7022862A763C9B1B885e11191c889E3",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 1663957,
    "holders": 51380
  },
  {
    "symbol": "MSTR",
    "name": "Strategy Inc. • Robinhood Token",
    "address": "0xec262a75e413fAfD0dF80480274532C79D42da09",
    "decimals": 18,
    "pool": "0x17578C0e0D15da44f31677263114F71aE76653EA",
    "fee": 10000,
    "assetIsToken0": false,
    "observationCardinality": 1500,
    "chainLiquidityUsd": 1443044,
    "holders": 6563
  },
  {
    "symbol": "GME",
    "name": "GameStop • Robinhood Token",
    "address": "0x1b0E319c6A659F002271B69dB8A7df2F911c153E",
    "decimals": 18,
    "pool": "0xE2b46c905E12Ab8E2f864e4821a4325884C1B126",
    "fee": 500,
    "assetIsToken0": true,
    "observationCardinality": 1500,
    "chainLiquidityUsd": 1442413,
    "holders": 35476
  },
  {
    "symbol": "TSM",
    "name": "Taiwan Semiconductor Manufacturing • Robinhood Token",
    "address": "0x58FfE4a942d3885bAa22D7520691F611EF09e7AA",
    "decimals": 18,
    "pool": "0x07e8Ea83D4C1340774c8965125e26e12bf943bf1",
    "fee": 10000,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 1247716,
    "holders": 6787
  },
  {
    "symbol": "RDDT",
    "name": "Reddit • Robinhood Token",
    "address": "0x05b37Fb53A299a1b874A619e1c4C404D52C36F4C",
    "decimals": 18,
    "pool": "0xa8744E76aED23B05F0126335E7BD38f7935D19fe",
    "fee": 10000,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 1167353,
    "holders": 17106
  },
  {
    "symbol": "TTWO",
    "name": "Take-Two Interactive Software • Robinhood Token",
    "address": "0x5e81213613b6B86EaB4c6c50d718d34359459786",
    "decimals": 18,
    "pool": "0xD9Ab4b7fAe6DC2f7020134Ec744A8F53Ef3E5E24",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 360,
    "chainLiquidityUsd": 1160638,
    "holders": 7189
  },
  {
    "symbol": "DJT",
    "name": "Trump Media & Technology Group Corp. • Robinhood Token",
    "address": "0x1D11f0496982706C5e14A514D4E79F2e6BdE4516",
    "decimals": 18,
    "pool": "0x31a89afd92F9397465649AD03226c52292fc1ae5",
    "fee": 10000,
    "assetIsToken0": true,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 1085771,
    "holders": 20571
  },
  {
    "symbol": "GOOGL",
    "name": "Alphabet Class A • Robinhood Token",
    "address": "0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3",
    "decimals": 18,
    "pool": "0x34D0dC122CF9A8Eb296fC5e0D3A233625D7d19b7",
    "fee": 500,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 1082436,
    "holders": 48983
  },
  {
    "symbol": "MSFT",
    "name": "Microsoft • Robinhood Token",
    "address": "0xe93237C50D904957Cf27E7B1133b510C669c2e74",
    "decimals": 18,
    "pool": "0xeb60bCD1D920ad6E102690CCFC6fB488899E1510",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 1010094,
    "holders": 44325
  },
  {
    "symbol": "COST",
    "name": "Costco • Robinhood Token",
    "address": "0x4EA005168D7F09a7A0Ba9D1DEf21a479950E44C2",
    "decimals": 18,
    "pool": "0x0a2121A50A09eD0796ae81F9c53fF9398355a398",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 911149,
    "holders": 13700
  },
  {
    "symbol": "PLTR",
    "name": "Palantir Technologies • Robinhood Token",
    "address": "0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A",
    "decimals": 18,
    "pool": "0x851680416A4f4E1c463d45171d61ACDdBc8554c0",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 805258,
    "holders": 34994
  },
  {
    "symbol": "LLY",
    "name": "Eli Lilly • Robinhood Token",
    "address": "0x8005d266423c7ea827372c9c864491e5786600ea",
    "decimals": 18,
    "pool": "0xF4274130137eeE20bAD928B593d992716516CEB9",
    "fee": 10000,
    "assetIsToken0": false,
    "observationCardinality": 256,
    "chainLiquidityUsd": 785706,
    "holders": 2220
  },
  {
    "symbol": "AMZN",
    "name": "Amazon • Robinhood Token",
    "address": "0x12f190a9F9d7D37a250758b26824B97CE941bF54",
    "decimals": 18,
    "pool": "0x8AC92DA74AB5F3b1d024Dc1943Ad7e15Dc4179Ef",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 745298,
    "holders": 37791
  },
  {
    "symbol": "RBLX",
    "name": "Roblox • Robinhood Token",
    "address": "0xF0C4BF4C582cb3836e98394b1d4e7B7281101bE8",
    "decimals": 18,
    "pool": "0x1BDB8e3A79Cb1a7F228808739311E23098D33d43",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 360,
    "chainLiquidityUsd": 691954,
    "holders": 5337
  },
  {
    "symbol": "SNAP",
    "name": "Snap Inc. • Robinhood Token",
    "address": "0xF6589F11Bc40b669e584073F428B05562F568733",
    "decimals": 18,
    "pool": "0x0EbD4650C9e641E9745b5A508A2D46935DFE753E",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 200,
    "chainLiquidityUsd": 683932,
    "holders": 399
  },
  {
    "symbol": "SGOV",
    "name": "iShares 0-3 Month Treasury Bond • Robinhood Token",
    "address": "0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5",
    "decimals": 18,
    "pool": "0xfAb520051f96F4D2a32c22B6a3dD7fFfdf231bFe",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 683439,
    "holders": 584
  },
  {
    "symbol": "SNDK",
    "name": "Sandisk Corporation • Robinhood Token",
    "address": "0xB90A19fF0Af67f7779afF50A882A9CfF42446400",
    "decimals": 18,
    "pool": "0xA1e1C9519cD5ae47e9A935645E1A7b935b944559",
    "fee": 10000,
    "assetIsToken0": false,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 628794,
    "holders": 24557
  },
  {
    "symbol": "AMD",
    "name": "AMD • Robinhood Token",
    "address": "0x86923f96303D656E4aa86D9d42D1e57ad2023fdC",
    "decimals": 18,
    "pool": "0x48D284A2A4d3DC1b3Da08231Fe44317e7e7Aa51f",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 587143,
    "holders": 36314
  },
  {
    "symbol": "USO",
    "name": "United States Oil Fund • Robinhood Token",
    "address": "0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344",
    "decimals": 18,
    "pool": "0x02175608F1b5E6b5ed221cCFdC7Be197D111D915",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 570398,
    "holders": 5320
  },
  {
    "symbol": "MRNA",
    "name": "Moderna, Inc. • Robinhood Token",
    "address": "0x43B07D15cE533bEc5476d70C22a78a1B2B662155",
    "decimals": 18,
    "pool": "0xA34d0667334074DF2d5BfD259e79E6B9cf1fA8Bf",
    "fee": 10000,
    "assetIsToken0": true,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 517982,
    "holders": 1141
  },
  {
    "symbol": "CRCL",
    "name": "Circle Internet Group • Robinhood Token",
    "address": "0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5",
    "decimals": 18,
    "pool": "0x654E4143e82a5824445Ade0824351C2A9ACD95a8",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 514647,
    "holders": 7724
  },
  {
    "symbol": "META",
    "name": "Meta Platforms • Robinhood Token",
    "address": "0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35",
    "decimals": 18,
    "pool": "0x107a7Cb40d8665360ba10E59471Af06150A50922",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1400,
    "chainLiquidityUsd": 484194,
    "holders": 30648
  },
  {
    "symbol": "INTC",
    "name": "Intel • Robinhood Token",
    "address": "0xc72b96e0E48ecd4DC75E1e45396e26300BC39681",
    "decimals": 18,
    "pool": "0x2e5a92f5013a64661A49312111be2e8aBd33F56a",
    "fee": 3000,
    "assetIsToken0": false,
    "observationCardinality": 1500,
    "chainLiquidityUsd": 439367,
    "holders": 24609
  },
  {
    "symbol": "FIG",
    "name": "Figma, Inc. • Robinhood Token",
    "address": "0x41F4267525a8AFf329540eF24fD83d9044758B33",
    "decimals": 18,
    "pool": "0xca5904C0a9d42F0Ec1Bf760FDf779907877144fD",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 200,
    "chainLiquidityUsd": 343179,
    "holders": 199
  },
  {
    "symbol": "LULU",
    "name": "Lululemon • Robinhood Token",
    "address": "0x4e62068525Ab11FE768e29dfD00ef909B9803016",
    "decimals": 18,
    "pool": "0x0F4227D27082B3BCA6818381b9ea6460275e49f4",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 300,
    "chainLiquidityUsd": 329223,
    "holders": 649
  },
  {
    "symbol": "DELL",
    "name": "Dell • Robinhood Token",
    "address": "0x941AE714EC6D8130c7B75d67160Ca08f1e7d11Dd",
    "decimals": 18,
    "pool": "0xc30c89cB7815A1488b7998D15eEC73961707Fc5a",
    "fee": 10000,
    "assetIsToken0": false,
    "observationCardinality": 1500,
    "chainLiquidityUsd": 320486,
    "holders": 3277
  },
  {
    "symbol": "JNJ",
    "name": "Johnson & Johnson • Robinhood Token",
    "address": "0x03DfbBE0AC4E7bCDaFd08eD41A400326B77D8c80",
    "decimals": 18,
    "pool": "0x8d39388EF11Bb78843130Bd74AB0e5d89fA76b30",
    "fee": 10000,
    "assetIsToken0": true,
    "observationCardinality": 300,
    "chainLiquidityUsd": 293935,
    "holders": 510
  },
  {
    "symbol": "UPS",
    "name": "UPS • Robinhood Token",
    "address": "0xf23250dac154D05Bb671CB0d0eBEf3c635c79CE2",
    "decimals": 18,
    "pool": "0x3Ab74C45DceCC6A62898204Dd42143a816B44CB1",
    "fee": 10000,
    "assetIsToken0": false,
    "observationCardinality": 200,
    "chainLiquidityUsd": 267833,
    "holders": 232
  },
  {
    "symbol": "AMC",
    "name": "AMC Entertainment Holdings, Inc. • Robinhood Token",
    "address": "0x05a3d1Cd21d0C88145E82600E62e7E496e0F222B",
    "decimals": 18,
    "pool": "0xaA34feA710a1A737840329051D81D3B0B7C564d5",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 300,
    "chainLiquidityUsd": 261916,
    "holders": 1222
  },
  {
    "symbol": "SLV",
    "name": "iShares Silver Trust • Robinhood Token",
    "address": "0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f",
    "decimals": 18,
    "pool": "0x8cB787e6c315D464775289BaD00FDD67d53Ecb3D",
    "fee": 3000,
    "assetIsToken0": true,
    "observationCardinality": 1801,
    "chainLiquidityUsd": 256338,
    "holders": 4590
  }
] as const;

export function assetBySymbol(symbol: string): EquityAsset | undefined {
  return EQUITY_ASSETS.find((a) => a.symbol.toLowerCase() === symbol.toLowerCase());
}

export function assetByAddress(address: string): EquityAsset | undefined {
  const needle = address.toLowerCase();
  return EQUITY_ASSETS.find((a) => a.address.toLowerCase() === needle);
}
