#!/usr/bin/env node
/**
 * Copies the compiled ABIs out of `contracts/out` into the SDK as typed constants, so the SDK can
 * never drift from the contracts it talks to. Run after `forge build`.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const CONTRACTS = [
  "SherwoodOracle",
  "SherwoodMarket",
  "SherwoodFactory",
  "SherwoodBasket",
  "SherwoodBasketOracle",
  "KinkedIrm",
];
const OUT = "packages/sdk/src/abis.ts";

let body = `// Generated by scripts/emit-abis.mjs from contracts/out. Do not hand-edit.
// Regenerate with: forge build --root contracts && node scripts/emit-abis.mjs
`;

for (const name of CONTRACTS) {
  const path = `contracts/out/${name}.sol/${name}.json`;
  if (!existsSync(path)) {
    console.error(`missing artifact ${path}; run \`forge build --root contracts\` first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  const constName = name.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase() + "_ABI";
  body += `\nexport const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

/** The one ERC-20 surface unique to Robinhood's tokenized equities. */
body += `
/** The members of Robinhood's \`Stock\` token that no ordinary ERC-20 has. */
export const STOCK_TOKEN_ABI = [
  { type: "function", name: "uiMultiplier", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "newUIMultiplier", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "effectiveAt", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOfUI", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "paused", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "tokenPaused", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "oraclePaused", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allowance", inputs: [{ type: "address" }, { type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ type: "address" }, { type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "transfer", inputs: [{ type: "address" }, { type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "permit",
    inputs: [
      { type: "address" }, { type: "address" }, { type: "uint256" },
      { type: "uint256" }, { type: "uint8" }, { type: "bytes32" }, { type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

/** USDG, which has neither EIP-2612 nor EIP-3009 on this chain. */
export const ERC20_ABI = [
  { type: "function", name: "balanceOf", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "allowance", inputs: [{ type: "address" }, { type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ type: "address" }, { type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
] as const;
`;

writeFileSync(OUT, body);
console.error(`wrote ${CONTRACTS.length} ABIs to ${OUT}`);
